//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroLog.Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Occupations> Occupations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<KayitliKullanicilar> KayitliKullanicilar { get; set; }
        public virtual DbSet<Ucuslar> Ucuslar { get; set; }
    
        public virtual ObjectResult<GunlukUcus_Result> GunlukUcus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukUcus_Result>("GunlukUcus");
        }
    
        public virtual ObjectResult<IdUcusListesi_Result> IdUcusListesi(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IdUcusListesi_Result>("IdUcusListesi", userIDParameter);
        }
    }
}
