//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroLog.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitliKullanicilar
    {
        public string KULLANICI_ADI { get; set; }
        public string SOYADI { get; set; }
        public string EPOSTA { get; set; }
        public string TELEFON { get; set; }
        public string ADRESI { get; set; }
        public string MESLEGI { get; set; }
        public string SIRKET_ADI { get; set; }
        public string SIRKET_EPOSTA { get; set; }
        public int SIRKET_TELEFONU { get; set; }
    }
}
