//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroLog.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucuslar
    {
        public string KULLANICI_ADI { get; set; }
        public string SIRKET_ADI { get; set; }
        public string UCUS_KODU { get; set; }
        public System.DateTime KALKIS_TARIHI { get; set; }
        public System.DateTime VARIS_TARIHI { get; set; }
        public string KALKIS { get; set; }
        public string VARIS { get; set; }
        public string VehicleName { get; set; }
    }
}
